"""Still-frame extraction and banner probing.

The fixtures under ``test_media/`` are deliberately tiny and purpose-built:

``clip.mp4``     2s @10fps, 64x64 — red for the first second, blue for the
                 second. Shorter than FRAME_SEEK_SECONDS, so it also proves
                 the walk back towards the start reaches 1.0s.
``short.mp4``    0.2s — shorter than every seek, so it reaches the no-seek
                 attempt.
``clip.webm``    a second container.
``rotated.mp4``  encoded 64x32 with a 90-degree display matrix, so the decoded
                 frame is 32x64 and the banner's dimensions are wrong.
``broken.mp4``   a truncated ``clip.mp4``.
``titles.mp4``   12s @10fps — a title card (white marks on black, ~3% of the
                 frame, as a real card is) for the first 6s, then a scene.
                 The frame at FRAME_SEEK_SECONDS is the card, so it exercises
                 the deeper retry.
``scene.mp4``    8s, that same scene throughout: the frame at
                 FRAME_SEEK_SECONDS is already good.
``outro.mp4``    10s — the scene for 4s, then black. The good frame is
                 *earlier* than the first attempt, so it exercises the walk
                 back towards the start.
``dark.mp4``     8s, black throughout: no offset has anything to find, and the
                 file must still be indexed.

The last four are 320x180 (a 64x64 frame is too small for a title card to
measure like a real one) and were generated by rendering PIL frames and
piping them to the bundled ffmpeg as image2pipe PNGs (``-c:v libx264
-pix_fmt yuv420p -g 10``).
"""

from __future__ import annotations

import io
import os
import subprocess
from pathlib import Path

import pytest
from fixtures import media_fixture_path
from PIL import Image

from photomap.backend import video as video_module
from photomap.backend.video import (
    DEEPER_SEEK_FALLBACK_SECONDS,
    FRAME_ENTROPY_FLOOR,
    FRAME_EXTRACT_TIMEOUT_SECONDS,
    FRAME_SEEK_SECONDS,
    MAX_FRAME_ATTEMPTS,
    MAX_FRAME_EDGE,
    VideoInfo,
    _frame_entropy,
    _has_decodable_video_stream,
    _next_deeper_seek,
    _parse_ffmpeg_banner,
    _seek_is_inside,
    extract_video_frame,
    ffmpeg_exe,
)

# A representative banner, captured from the bundled ffmpeg. Parser tests run
# against this fixed string so they need no binary at all.
SAMPLE_BANNER = """Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'clip.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.1.100
  Duration: 00:01:05.50, start: 0.000000, bitrate: 8 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(progressive), 640x480 [SAR 1:1 DAR 4:3], 4 kb/s, 29.97 fps, 30 tbr, 10240 tbn (default)
      Metadata:
        handler_name    : VideoHandler
"""


requires_ffmpeg = pytest.mark.skipif(
    ffmpeg_exe() is None, reason="no bundled ffmpeg binary on this platform"
)


# --------------------------------------------------------------------------
# Banner parsing (no ffmpeg required)
# --------------------------------------------------------------------------


def test_parse_banner_extracts_duration_fps_codec_container():
    info = _parse_ffmpeg_banner(SAMPLE_BANNER)
    assert info["container"] == "mov,mp4,m4a,3gp,3g2,mj2"
    assert info["duration"] == pytest.approx(65.5)
    assert info["codec"] == "h264"
    assert info["fps"] == pytest.approx(29.97)


def test_parse_banner_never_reports_dimensions():
    """Dimensions must come from the decoded frame, never the banner.

    ffmpeg autorotates on decode, so a portrait phone video's banner reports
    the pre-rotation size. Asserting the parser has no opinion at all makes
    that structural rather than merely tested.
    """
    info = _parse_ffmpeg_banner(SAMPLE_BANNER)
    assert "width" not in info
    assert "height" not in info


def test_parse_banner_tolerates_missing_duration_line():
    banner = SAMPLE_BANNER.replace(
        "  Duration: 00:01:05.50, start: 0.000000, bitrate: 8 kb/s\n", ""
    )
    info = _parse_ffmpeg_banner(banner)
    assert "duration" not in info
    # The other fields still parse — one miss degrades one field.
    assert info["codec"] == "h264"
    assert info["container"] == "mov,mp4,m4a,3gp,3g2,mj2"


def test_parse_banner_of_garbage_returns_empty_dict():
    assert _parse_ffmpeg_banner("not a banner at all") == {}


def test_parse_banner_returns_plain_python_scalars():
    """``/get_metadata`` runs json.dumps over the metadata dict."""
    import json

    info = _parse_ffmpeg_banner(SAMPLE_BANNER)
    json.dumps(info)  # must not raise
    assert type(info["duration"]) is float
    assert type(info["fps"]) is float
    assert type(info["codec"]) is str


def test_parse_banner_ignores_audio_stream_numbers():
    """The fps must be read from the video stream line, not an audio one."""
    banner = SAMPLE_BANNER + (
        "  Stream #0:1[0x2](und): Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s\n"
    )
    info = _parse_ffmpeg_banner(banner)
    assert info["fps"] == pytest.approx(29.97)


# --------------------------------------------------------------------------
# Frame extraction
# --------------------------------------------------------------------------


@requires_ffmpeg
def test_extract_returns_rgb_frame_and_populated_info():
    result = extract_video_frame(media_fixture_path("clip.mp4"))
    assert result is not None
    frame, info = result

    assert isinstance(frame, Image.Image)
    assert frame.mode == "RGB"
    assert frame.size == (64, 64)

    assert isinstance(info, VideoInfo)
    assert info.duration == pytest.approx(2.0, abs=0.2)
    assert info.fps == pytest.approx(10.0)
    assert info.codec == "h264"
    assert info.width == 64 and info.height == 64
    assert info.playable is True


@requires_ffmpeg
def test_extract_seeks_past_the_opening_frames(monkeypatch):
    """A seek must actually happen rather than frame 0 being taken.

    clip.mp4 is 2s, so the 5.0s seek finds nothing and the aimed retry reaches
    1.0s. Frame 0 of consumer video is very often black or a fade-in, which is
    a poor CLIP subject.

    Asserted on the seek offsets, not on the returned pixel. Both halves of
    clip.mp4 are solid colours that score exactly -0.0, so which one comes
    back is decided by ``score > best`` being strict and blue being decoded
    first — a tie-break, not the behaviour under test. Any encoder change that
    gave red a fractionally higher entropy would have failed a colour
    assertion while the seeking it was meant to cover still worked.
    """
    attempts = _record_attempts(monkeypatch)
    result = extract_video_frame(media_fixture_path("clip.mp4"))

    assert result is not None
    seeks = _seeks(attempts)
    assert seeks[0] == video_module.FRAME_SEEK_SECONDS
    assert 1.0 in seeks, f"expected a retry aimed into the file, got {seeks}"


@requires_ffmpeg
def test_a_short_clip_does_not_re_read_a_frame_it_already_rejected(monkeypatch):
    """No attempt may land within the gap of an offset already decoded.

    The floor in _next_deeper_seek only holds a candidate away from the
    attempt that just ran. Once the no-seek rung had run — decoding position 0
    and so setting the floor at 0 + the gap — the deeper ladder re-armed from
    the start of the file and queued 0.1 x duration, which on clip.mp4 is
    1.2s: two tenths of a second from the 1.0s frame it had already decoded
    and rejected, inside the same solid-colour second. That spent one of the
    four permitted spawns on a frame that could not differ.
    """
    attempts = _record_attempts(monkeypatch)
    extract_video_frame(media_fixture_path("clip.mp4"))

    positions = sorted(0.0 if seek is None else seek for seek in _seeks(attempts))
    gaps = [b - a for a, b in zip(positions, positions[1:], strict=False)]
    assert all(gap >= video_module.MIN_DEEPER_SEEK_GAP_SECONDS for gap in gaps), (
        f"attempts {positions} contain a pair closer than "
        f"{video_module.MIN_DEEPER_SEEK_GAP_SECONDS}s: gaps {gaps}"
    )


def test_the_deeper_ladder_stops_at_max_deeper_attempts(monkeypatch):
    """The cap is only observable on a file long enough to have a 4th rung.

    Every fixture is at most 12s, where the capped and uncapped ladders
    coincide, so no other test notices this constant changing. At 600s the
    third deeper fraction (0.6 -> 360s) is a real candidate, and the cap is
    what makes the 4th attempt the walk-back to 1.0s instead.

    Fully synthetic: a real decode cannot be used because no fixture is long
    enough to seek 210s into, and rewriting only the banner of a short file
    makes the deep rungs return nothing, which sends the ladder down the
    short-clip path instead of the one under test.
    """
    seeks: list[float | None] = []

    def long_and_dark(args, timeout):
        seeks.append(float(args[args.index("-ss") + 1]) if "-ss" in args else None)
        return subprocess.CompletedProcess(
            args, returncode=0, stdout=_DARK_PNG, stderr=_TEN_MINUTE_BANNER
        )

    monkeypatch.setattr(video_module, "_run_ffmpeg", long_and_dark)
    result = extract_video_frame(media_fixture_path("dark.mp4"))

    assert result is not None, "a dark film still has to yield a poster"
    assert seeks == [5.0, 60.0, 210.0, 1.0], f"unexpected ladder {seeks}"


def _dark_png() -> bytes:
    buffer = io.BytesIO()
    Image.new("RGB", (320, 180), (0, 0, 0)).save(buffer, format="PNG")
    return buffer.getvalue()


_DARK_PNG = _dark_png()

# Shaped after a real ffmpeg banner (see _banner_duration and
# _has_decodable_video_stream): the duration line is what the ladder computes
# its fractions from, and the Stream line is what proves this is real video
# rather than an audio file's cover art.
_TEN_MINUTE_BANNER = (
    b"  Duration: 00:10:00.00, start: 0.000000, bitrate: 3 kb/s\n"
    b"  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), "
    b"yuv420p(progressive), 320x180, 2 kb/s, 10 fps, 10 tbr, 10240 tbn (default)\n"
)


@requires_ffmpeg
def test_extract_falls_back_to_first_frame_for_sub_second_video():
    """short.mp4 is 0.2s: every offset is past its end, so frame 0 is used."""
    result = extract_video_frame(media_fixture_path("short.mp4"))
    assert result is not None
    frame, info = result
    assert frame.size == (48, 32)
    r, g, b = frame.getpixel((24, 16))
    assert g > 100 and r < 100, f"expected green, got {(r, g, b)}"
    assert info.width == 48 and info.height == 32


@requires_ffmpeg
def test_extract_uses_decoded_size_not_banner_size():
    """rotated.mp4's banner says 64x32; ffmpeg autorotates to 32x64."""
    frame, info = extract_video_frame(media_fixture_path("rotated.mp4"))
    assert frame.size == (32, 64)
    assert (info.width, info.height) == (32, 64)


@requires_ffmpeg
def test_extract_handles_a_second_container():
    frame, info = extract_video_frame(media_fixture_path("clip.webm"))
    assert frame.size == (64, 64)
    assert info.container is not None and "webm" in info.container.lower()
    assert info.playable is True


@requires_ffmpeg
def test_extract_returns_none_for_truncated_file():
    assert extract_video_frame(media_fixture_path("broken.mp4")) is None


@requires_ffmpeg
def test_extract_returns_none_for_a_non_video(tmp_path):
    junk = tmp_path / "notes.mp4"
    junk.write_text("this is not a video")
    assert extract_video_frame(junk) is None


@requires_ffmpeg
def test_extract_returns_none_for_missing_file(tmp_path):
    assert extract_video_frame(tmp_path / "nope.mp4") is None


@requires_ffmpeg
def test_extract_downscales_oversized_frames(monkeypatch):
    """A 4K still would otherwise be megabytes on disk and over the wire."""
    monkeypatch.setattr(video_module, "MAX_FRAME_EDGE", 32)
    frame, _info = extract_video_frame(media_fixture_path("clip.mp4"))
    assert max(frame.size) <= 32


def test_reported_resolution_is_the_source_not_the_thumbnail(monkeypatch):
    """VideoInfo must describe the video, not the downscaled poster.

    thumbnail() resizes in place, so reading frame.width after it would label
    every 4K video 2048-wide — and the cap is applied to the very frames whose
    true resolution matters most.
    """
    monkeypatch.setattr(video_module, "MAX_FRAME_EDGE", 32)
    frame, info = extract_video_frame(media_fixture_path("clip.mp4"))

    assert max(frame.size) <= 32, "the stored frame is still capped"
    assert (info.width, info.height) == (64, 64), "but the source size is reported"


@requires_ffmpeg
def test_max_frame_edge_is_sane():
    assert MAX_FRAME_EDGE >= 512


@requires_ffmpeg
def test_extract_returns_none_on_timeout():
    """A wedged ffmpeg must be killed and skipped, not hang indexing."""
    result = extract_video_frame(media_fixture_path("clip.mp4"), timeout=0.001)
    assert result is None


def test_extract_returns_none_when_ffmpeg_unavailable(monkeypatch):
    """On musl/armv7/win_arm64 the sdist ships no binary.

    Videos must then be skipped cleanly — one warning, image indexing
    untouched — rather than raising once per file inside a worker thread.
    """
    monkeypatch.setattr(video_module, "ffmpeg_exe", lambda: None)
    assert extract_video_frame(media_fixture_path("clip.mp4")) is None


@requires_ffmpeg
def test_playable_flag_reflects_container(tmp_path):
    """Index-only containers are still extracted, just flagged unplayable."""
    avi = tmp_path / "clip.avi"
    avi.write_bytes(media_fixture_path("clip.mp4").read_bytes())
    # Content is really an mp4; ffmpeg sniffs content, not the extension, so
    # extraction succeeds and only the playability hint follows the suffix.
    result = extract_video_frame(avi)
    assert result is not None
    _frame, info = result
    assert info.playable is False


@requires_ffmpeg
def test_ffmpeg_exe_is_cached():
    """Resolved once per process rather than per video file."""
    assert ffmpeg_exe() == ffmpeg_exe()


@requires_ffmpeg
def test_ffmpeg_exe_resolves_to_an_executable_path():
    """A bare name from PATH is resolved, not handed back unusable.

    get_ffmpeg_exe() returns $IMAGEIO_FFMPEG_EXE unvalidated and can fall back
    to the literal string "ffmpeg", so a non-None answer is not on its own
    evidence anything can be run.
    """
    exe = ffmpeg_exe()
    assert os.path.isabs(exe)
    assert Path(exe).exists()


def test_a_transient_probe_failure_is_not_cached(monkeypatch, tmp_path):
    """A fork failure under memory pressure must not disable video forever.

    The stand-in binary is a real file under ``tmp_path`` rather than a
    hardcoded path. ``ffmpeg_exe`` resolves a non-absolute candidate through
    ``shutil.which``, and what counts as absolute is platform- *and*
    version-specific: Python 3.13 changed ``ntpath.isabs`` so a leading slash
    with no drive letter is no longer absolute on Windows. A literal
    "/usr/bin/ffmpeg" therefore passed on win/3.10 and failed on win/3.14.
    A tmp_path is absolute everywhere, and being a real file means the
    existence check needs no patching either.
    """
    video_module._reset_ffmpeg_exe_cache()
    try:
        stand_in = tmp_path / "ffmpeg"
        stand_in.write_text("")
        calls = []

        def flaky():
            calls.append(1)
            if len(calls) == 1:
                raise OSError("Cannot allocate memory")
            return str(stand_in)

        import imageio_ffmpeg

        monkeypatch.setattr(imageio_ffmpeg, "get_ffmpeg_exe", flaky)

        assert video_module.ffmpeg_exe() is None
        # The next call retries rather than returning a memoized failure.
        assert video_module.ffmpeg_exe() == str(stand_in)
        assert len(calls) == 2
    finally:
        # Restore the real probe result for any test that runs after this one.
        video_module._reset_ffmpeg_exe_cache()


@requires_ffmpeg
def test_ffmpeg_exe_points_at_a_real_binary():
    assert Path(ffmpeg_exe()).exists()


# --------------------------------------------------------------------------
# Banner parsing against hostile input
# --------------------------------------------------------------------------

# A real banner shape: ffmpeg prints the file's OWN tags, in a Metadata block,
# BEFORE the Duration and Stream lines it generates itself.
HOSTILE_BANNER = """Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'clip.mp4':
  Metadata:
    major_brand     : isom
    comment         : Duration: 12:34:56.00
    description     : Stream #0:0: Video: fakecodec, 999 fps
  Duration: 00:00:02.00, start: 0.000000, bitrate: 8 kb/s
  Stream #0:0[0x1](und): Video: h264 (High), yuv420p, 64x64, 10 fps, 10 tbr (default)
      Metadata:
        handler_name    : VideoHandler
"""


def test_metadata_tags_cannot_hijack_the_duration():
    """Tags are file-controlled, so any downloaded video can carry these."""
    info = _parse_ffmpeg_banner(HOSTILE_BANNER)
    assert info["duration"] == pytest.approx(2.0)


def test_metadata_tags_cannot_hijack_the_codec_or_fps():
    info = _parse_ffmpeg_banner(HOSTILE_BANNER)
    assert info["codec"] == "h264"
    assert info["fps"] == pytest.approx(10.0)


def test_a_tag_holding_newlines_cannot_fake_a_report_line():
    """Blocks are found by indentation, so an embedded newline doesn't help."""
    banner = HOSTILE_BANNER.replace(
        "    comment         : Duration: 12:34:56.00",
        "    comment         : multi\n      Duration: 44:44:44.00",
    )
    assert _parse_ffmpeg_banner(banner)["duration"] == pytest.approx(2.0)


def test_a_path_containing_the_delimiter_does_not_leak_into_the_container():
    """Greedy matching spliced the user's absolute path into the container."""
    banner = (
        "Input #0, mov,mp4,m4a,3gp,3g2,mj2, from "
        "'/photos/Trip, from Rome/clip.mp4':\n"
        "  Duration: 00:00:02.00, start: 0.000000, bitrate: 8 kb/s\n"
    )
    container = _parse_ffmpeg_banner(banner)["container"]
    assert container == "mov,mp4,m4a,3gp,3g2,mj2"
    assert "/photos" not in container


def test_an_absurd_duration_costs_only_that_field():
    """int(h)*3600 on a bignum raises OverflowError on the float conversion."""
    banner = "  Duration: " + "9" * 400 + ":00:00.00, start: 0.0\n"
    info = _parse_ffmpeg_banner(banner)
    assert "duration" not in info


def test_cover_art_is_not_treated_as_a_video_stream():
    """An .ogg is usually audio; its album art is offered as a video stream."""
    banner = (
        "Input #0, ogg, from 'song.ogg':\n"
        "  Duration: 00:03:12.00, start: 0.000000, bitrate: 128 kb/s\n"
        "  Stream #0:0: Audio: vorbis, 44100 Hz, stereo, fltp, 128 kb/s\n"
        "  Stream #0:1: Video: mjpeg (attached pic), yuvj420p, 600x600, 90k tbr\n"
    )
    assert _has_decodable_video_stream(banner) is False


def test_a_real_video_stream_is_recognized():
    assert _has_decodable_video_stream(HOSTILE_BANNER) is True


# --------------------------------------------------------------------------
# Scoring a frame
# --------------------------------------------------------------------------


def _solid(color, size=(320, 180)) -> Image.Image:
    return Image.new("RGB", size, color)


def test_a_solid_frame_carries_no_information():
    """Black, and a slate of any other brightness, both score zero."""
    assert _frame_entropy(_solid((0, 0, 0))) == 0.0
    assert _frame_entropy(_solid((128, 128, 128))) == 0.0
    assert _frame_entropy(_solid((40, 90, 200))) == 0.0


def test_titles_over_black_score_below_the_floor():
    """Two levels carry almost nothing, however sharp the text.

    This is the frame a fixed seek lands on in a film with a title sequence,
    and the reason the score is entropy rather than contrast: the standard
    deviation of this frame is enormous.
    """
    frame = _solid((0, 0, 0))
    for x in range(70, 250, 26):
        frame.paste(_solid((255, 255, 255), (16, 14)), (x, 86))
    assert _frame_entropy(frame) < FRAME_ENTROPY_FLOOR


def test_a_dark_but_real_scene_scores_above_the_floor():
    """A night scene must survive. It is almost entirely dark, so a
    dark-pixel count would reject it; what separates it from a title card is
    that it has tone everywhere rather than two levels."""
    frame = Image.new("RGB", (320, 180))
    frame.putdata(
        [(v // 8, v // 8, max(0, v // 8 - 2)) for v in range(180) for _ in range(320)]
    )
    assert _frame_entropy(frame) > FRAME_ENTROPY_FLOOR


def test_ordinary_content_scores_well_above_the_floor():
    """A daylight frame is not near the threshold; it is nowhere near it."""
    frame = Image.new("RGB", (320, 180))
    frame.putdata(
        [
            (60 + x // 3, 90 + y // 4, 200 - x // 4)
            for y in range(180)
            for x in range(320)
        ]
    )
    assert _frame_entropy(frame) > 4 * FRAME_ENTROPY_FLOOR


def test_an_unmeasurable_frame_is_always_kept():
    """The score is an optimisation hint; it must never lose a frame."""

    class Hostile:
        def convert(self, _mode):
            raise ValueError("no")

    assert _frame_entropy(Hostile()) == float("inf")


def test_the_floor_sits_between_the_junk_and_content_bands():
    """Calibrated against a labelled corpus of synthetic-but-realistic frames
    and real encodes. Junk measured 0.0 (black) to 0.65 (a dense end-credit
    crawl); the lowest real content measured 1.07 (an overcast snowfield).
    A floor outside that gap is a mis-set threshold, not a preference."""
    assert 0.66 <= FRAME_ENTROPY_FLOOR <= 1.05


# --------------------------------------------------------------------------
# Choosing where to look
# --------------------------------------------------------------------------


def test_a_seek_past_the_end_is_not_worth_an_attempt():
    assert _seek_is_inside(1.0, 0.2) is False
    assert _seek_is_inside(1.0, 30.0) is True


def test_a_seek_is_attempted_when_the_duration_is_unknown():
    """Some containers report no duration; that is not a reason to give up."""
    assert _seek_is_inside(5.0, None) is True
    assert _seek_is_inside(5.0, 0.0) is True
    assert _seek_is_inside(None, 0.2) is True


def test_deeper_seek_is_proportional_to_the_duration():
    """A fixed offset cannot cover a title sequence, whose length scales with
    the runtime."""
    assert _next_deeper_seek(5.0, 600.0, set()) == pytest.approx(60.0)


def test_deeper_seek_skips_candidates_too_close_to_the_rejected_frame():
    """0.1 of a 30s clip is 3s — earlier than the frame just rejected."""
    assert _next_deeper_seek(5.0, 30.0, set()) == pytest.approx(10.5)


def test_deeper_seek_advances_past_what_was_already_tried():
    assert _next_deeper_seek(60.0, 600.0, {5.0, 60.0}) == pytest.approx(210.0)


def test_deeper_seek_gives_up_when_nothing_is_far_enough_in():
    assert _next_deeper_seek(5.0, 6.0, set()) is None


def test_deeper_seek_stays_clear_of_the_end(monkeypatch):
    """Seeking to the last instant yields nothing, or the closing fade."""
    monkeypatch.setattr(video_module, "DEEPER_SEEK_FRACTIONS", (0.999,))
    assert _next_deeper_seek(5.0, 30.0, set()) is None
    monkeypatch.setattr(video_module, "DEEPER_SEEK_FRACTIONS", (0.9,))
    assert _next_deeper_seek(5.0, 30.0, set()) == pytest.approx(27.0)


def test_deeper_seek_without_a_duration_uses_a_fixed_offset(monkeypatch):
    """Some containers report no duration; one blind attempt is still worth
    making."""
    monkeypatch.setattr(video_module, "DEEPER_SEEK_FALLBACK_SECONDS", 30.0)
    assert _next_deeper_seek(5.0, None, set()) == 30.0
    assert _next_deeper_seek(5.0, None, {30.0}) is None
    assert DEEPER_SEEK_FALLBACK_SECONDS > 0


def test_a_bogus_duration_still_produces_an_offset_ffmpeg_can_parse():
    """``Duration: 596523:14:07.99`` is what ffmpeg prints for a stream with
    no valid duration. %g would render a fraction of it as '2.14748e+08',
    which ffmpeg then refuses as an invalid argument."""
    deeper = _next_deeper_seek(5.0, 2147483647.99, {5.0})
    args = video_module._frame_command(Path("clip.mp4"), deeper)
    assert "e+" not in args[args.index("-ss") + 1]


# --------------------------------------------------------------------------
# Walking the ladder
# --------------------------------------------------------------------------


def _record_attempts(monkeypatch) -> list[tuple[float | None, float]]:
    """Capture the -ss value and the timeout of every ffmpeg attempt."""
    attempts: list[tuple[float | None, float]] = []
    real = video_module._run_ffmpeg

    def spy(args, timeout):
        seek = float(args[args.index("-ss") + 1]) if "-ss" in args else None
        attempts.append((seek, timeout))
        return real(args, timeout)

    monkeypatch.setattr(video_module, "_run_ffmpeg", spy)
    return attempts


def _seeks(attempts) -> list[float | None]:
    return [seek for seek, _timeout in attempts]


@requires_ffmpeg
def test_a_good_frame_costs_exactly_one_ffmpeg_run(monkeypatch):
    """The default path, on the shape of file most of a collection is: the
    retries must not become a tax on every video."""
    attempts = _record_attempts(monkeypatch)

    frame, _info = extract_video_frame(media_fixture_path("scene.mp4"))

    assert _seeks(attempts) == [FRAME_SEEK_SECONDS]
    assert _frame_entropy(frame) >= FRAME_ENTROPY_FLOOR


@requires_ffmpeg
def test_extract_retries_deeper_past_a_title_sequence(monkeypatch):
    """titles.mp4 is a title card until 6s; the 5s frame must be rejected."""
    attempts = _record_attempts(monkeypatch)

    frame, info = extract_video_frame(media_fixture_path("titles.mp4"))

    r, g, b = frame.getpixel((160, 90))
    assert (g > 120 and r < 120), f"expected the scene, got {(r, g, b)}"
    assert info.duration == pytest.approx(12.0, abs=0.3)
    assert _seeks(attempts) == [FRAME_SEEK_SECONDS, pytest.approx(7.2)], (
        "one deeper attempt, at 0.6 of the duration"
    )


@requires_ffmpeg
def test_extract_walks_back_when_the_content_is_at_the_start(monkeypatch):
    """outro.mp4 runs 4s of scene, then 6s of black.

    Nothing at or beyond the first attempt is any good, so the search has to
    be willing to look *earlier* than where it started. Settling for the
    frame already in hand would put a black tile on a video whose content is
    right there at the front.
    """
    attempts = _record_attempts(monkeypatch)

    frame, _info = extract_video_frame(media_fixture_path("outro.mp4"))

    assert _frame_entropy(frame) >= FRAME_ENTROPY_FLOOR, "the scene, not the black tail"
    assert _seeks(attempts)[-1] == 1.0, "the last attempt walked back to the start"


@requires_ffmpeg
def test_a_short_clip_aims_its_retry_at_the_middle_of_the_file(monkeypatch):
    """The first attempt lands past the end of a clip shorter than the seek,
    but its banner still reports the duration — so the retry is aimed rather
    than guessed, and lands somewhere better than a fixed offset would."""
    monkeypatch.setattr(video_module, "SHORT_FILE_SEEK_FRACTION", 0.25)
    attempts = _record_attempts(monkeypatch)

    extract_video_frame(media_fixture_path("clip.mp4"))  # 2.0s

    assert _seeks(attempts)[:2] == [FRAME_SEEK_SECONDS, pytest.approx(0.5)]


@requires_ffmpeg
def test_the_best_frame_wins_when_every_frame_is_below_the_floor(monkeypatch):
    """A retry that decodes a better frame must not throw it away.

    With the floor unreachable, every frame titles.mp4 offers is 'empty', so
    the search runs to exhaustion — and what comes back has to be the best
    of what it saw, not the first.
    """
    monkeypatch.setattr(video_module, "FRAME_ENTROPY_FLOOR", 99.0)

    frame, _info = extract_video_frame(media_fixture_path("titles.mp4"))

    r, g, b = frame.getpixel((160, 90))
    assert (g > 120 and r < 120), f"expected the scene, got the title card {(r, g, b)}"


@requires_ffmpeg
def test_an_entirely_dark_video_is_still_extracted(monkeypatch):
    """Every attempt comes back empty, and a frame is returned anyway.

    Returning None here would drop the file from the album entirely, which is
    far worse than a dark poster.
    """
    attempts = _record_attempts(monkeypatch)

    result = extract_video_frame(media_fixture_path("dark.mp4"))

    assert result is not None
    frame, info = result
    assert frame.size == (320, 180)
    assert info.duration == pytest.approx(8.0, abs=0.3)
    assert _frame_entropy(frame) < FRAME_ENTROPY_FLOOR, "there was nothing to find"
    assert len(attempts) > 1, "and it did look elsewhere first"
    assert len(attempts) <= MAX_FRAME_ATTEMPTS, "but not without limit"


@requires_ffmpeg
def test_a_stalled_seek_skips_straight_to_the_no_seek_attempt(monkeypatch):
    """Seeking is what stalls on a slow mount, so retrying a shallower seek
    just buys a second timeout. A wedged file must cost two attempts, not one
    per rung of the ladder."""
    real = video_module._run_ffmpeg

    def stall_the_seek(args, timeout):
        if "-ss" in args:
            return None  # what _run_ffmpeg returns on a timeout
        return real(args, timeout)

    monkeypatch.setattr(video_module, "_run_ffmpeg", stall_the_seek)
    attempts = _record_attempts(monkeypatch)  # outermost, so it sees every attempt

    frame, _info = extract_video_frame(media_fixture_path("clip.mp4"))

    assert _seeks(attempts) == [FRAME_SEEK_SECONDS, None]
    r, _g, _b = frame.getpixel((32, 32))
    assert r > 200, "the no-seek attempt returns the red opening frame"


@requires_ffmpeg
def test_the_whole_file_is_bounded_by_twice_the_timeout(monkeypatch):
    """``video_cache.ensure`` and the thumbnail route both size their own
    locking and threadpool behaviour on this ceiling, so the ladder may not
    raise it however many rungs it grows."""
    attempts = _record_attempts(monkeypatch)
    clock = iter([0.0, 0.0, 55.0, 90.0, 130.0, 200.0, 300.0])
    last = [0.0]

    class SlowClock:
        def monotonic(self):
            last[0] = next(clock, last[0] + 100.0)
            return last[0]

    monkeypatch.setattr(video_module, "time", SlowClock())

    extract_video_frame(media_fixture_path("dark.mp4"))

    # The clock reports 0s, 55s and 90s elapsed at the three attempt sites,
    # against a 120s budget: full timeouts while there is room, then whatever
    # is left, then nothing.
    assert [timeout for _seek, timeout in attempts] == [
        FRAME_EXTRACT_TIMEOUT_SECONDS,
        FRAME_EXTRACT_TIMEOUT_SECONDS,
        30.0,
    ]
    assert len(attempts) < MAX_FRAME_ATTEMPTS, "the deadline cut the search short"


@requires_ffmpeg
def test_an_explicit_no_seek_request_does_not_seek(monkeypatch):
    """seek_seconds=0 asks for frame 0. The retry machinery must not
    reintroduce a seek behind the caller's back."""
    attempts = _record_attempts(monkeypatch)

    extract_video_frame(media_fixture_path("dark.mp4"), seek_seconds=0)

    assert _seeks(attempts) == [None]
