name: Deploy to PyPi

on:
  workflow_call:
  workflow_dispatch:

jobs:
  pypi-deploy:
    runs-on: ubuntu-latest
    environment: pypi

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(python -c "
          try:
              import tomllib
              with open('pyproject.toml', 'rb') as f:
                  data = tomllib.load(f)
              print(data['project']['version'])
          except Exception as e:
              print(f'Error reading version: {e}', file=sys.stderr)
              exit(1)
          ")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/