name: Build macOS .dmg
on:
  workflow_call:
  workflow_dispatch:
jobs:
  build-macos-dmg:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install project dependencies
        run: |
          # install your project so py2app can discover imports;
          # adjust if you prefer a requirements file: pip install -r requirements.txt
          python -m pip install .

      - name: Install py2app
        run: python -m pip install py2app

      - name: Build .app bundle (with debugging info)
        run: |
          set -euo pipefail
          # ensure py2app is installed into this Python env
          python -m pip install --upgrade py2app
          SCRIPTDIR=$(python -c "import sysconfig, os; print(sysconfig.get_path('scripts'))")
          echo "Python scripts dir: $SCRIPTDIR"
          if [ -x "$SCRIPTDIR/py2app" ]; then
            "$SCRIPTDIR/py2app"
          elif [ -x "$SCRIPTDIR/py2applet" ]; then
            # older py2app installs 'py2applet' entrypoint
            "$SCRIPTDIR/py2applet" -v
          else
            echo "py2app script not found in $SCRIPTDIR"
            ls -la "$SCRIPTDIR" || true
            python -m pip show py2app
            exit 1
          fi

      - name: Create .dmg
        run: |
          # use the dist dir configured in pyproject.toml (dist)
          hdiutil create -volname "PhotoMapAI" -srcfolder dist/PhotoMapAI.app -ov -format UDZO PhotoMapAI.dmg

      - name: Upload .dmg
        uses: actions/upload-artifact@v4
        with:
          name: PhotoMapAI.dmg
          path: PhotoMapAI.dmg
